name: push_t_env
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - numpy
  - zarr
  - pytorch
  - torchvision
  - torchaudio
  - pip
  - pip:
    - diffusers>=0.15.0
    - huggingface-hub>=0.15.0
    - transformers>=4.30.0
    - gym
    - pygame
    - pymunk
    - shapely
    - opencv-python
    - scikit-image
    - scikit-video
    - tqdm
    - gdown